# Generated by Django 4.1 on 2022-08-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactjob', '0002_job_img_job_level_job_webiste_alter_job_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='webiste',
            new_name='website',
        ),
    ]
